{% set name = "pyee" %}
{% set version = "13.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b391e3c5a434d1f5118a25615001dbc8f669cf410ab67d04c4d4e07c55481c37

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - wheel
  run:
    - python >={{ python_min }}
    - typing_extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pyee
  commands:
    - python -m pip check

about:
  home: https://github.com/jfhbrook/pyee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of node.js's EventEmitter to python.
  doc_url: https://pyee.readthedocs.io/
  dev_url: https://github.com/jfhbrook/pyee

extra:
  recipe-maintainers:
    - mxschmitt
    - kiwi0fruit
