{% set name = "pyee" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27c682bce60bdadc5d3e23eacd4101df328c0280884a3d9c07f3a4e3e595de27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - wheel
  run:
    - python >=3.8
    - typing_extensions

test:
  requires:
    - pip
  imports:
    - pyee
  commands:
    - python -m pip check

about:
  home: https://github.com/jfhbrook/pyee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of node.js's EventEmitter to python.
  doc_url: https://pyee.readthedocs.io/
  dev_url: https://github.com/jfhbrook/pyee

extra:
  recipe-maintainers:
    - mxschmitt
    - kiwi0fruit
