{% set name = "pyee" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92dacc5bd2bdb8f95aa8dd2585d47ca1c4840e2adb95ccf90034d64f725bfd31

build:
  noarch: python
  number: 0
  script: cd {{ RECIPE_DIR }} && {{ PYTHON }} builder.py

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - pip
  imports:
    - pyee
  commands:
    - python -m pip check

about:
  home: https://github.com/jfhbrook/pyee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of node.js's EventEmitter to python.
  doc_url: https://pyee.readthedocs.io/
  dev_url: https://github.com/jfhbrook/pyee

extra:
  recipe-maintainers:
    - mxschmitt
    - kiwi0fruit
